SELECT T1.*, T3.ENTER_CD AS T3_ENTER_CD, T3.SABUN AS T3_SABUN, T3.APPL_SEQ AS T3_APPL_SEQ, T3.SDATE, T3.EDATE -- T2의 모든 컬럼을 가져오려면 여기에 명시
FROM TTIM132 T1
JOIN (
    SELECT
        T2.ENTER_CD,
        T2.SABUN,
        T2.APPL_SEQ,
        T2.SDATE,
        T2.EDATE,
        -- T2의 다른 필요한 컬럼들도 여기에 포함시킵니다.
        ROW_NUMBER() OVER (PARTITION BY T2.ENTER_CD, T2.SABUN, T2.SDATE, T2.EDATE ORDER BY T2.APPL_SEQ DESC) as rn
        -- PARTITION BY에 T2.SDATE, T2.EDATE를 포함시켜 각 YMD 범위별로 MAX APPL_SEQ를 찾습니다.
    FROM TTIM131 T2
) T3 ON T1.ENTER_CD = T3.ENTER_CD
AND T1.SABUN = T3.SABUN
AND T1.YMD BETWEEN T3.SDATE AND T3.EDATE -- T1.YMD가 T2의 SDATE, EDATE 범위 내에 있어야 합니다.
AND T1.APPL_SEQ = T3.APPL_SEQ -- T1.APPL_SEQ가 T3에서 찾아낸 MAX(APPL_SEQ)와 같아야 합니다.
AND T3.rn = 1 -- 각 그룹에서 APPL_SEQ가 가장 높은 레코드만 선택
WHERE T1.ENTER_CD = 'HX'
AND T1.SABUN = '09700062'
AND T1.YMD = '20250617';