SELECT COUNT(*) FROM tben753_univ_202501;
SELECT COUNT(*) FROM tben753_univ_202401;
SELECT COUNT(*) FROM tben753_univ_202302;
SELECT * FROM tben753_univ_202301;

ALTER TABLE TBEN753
ADD DAY_NIGHT VARCHAR2(1);

COMMENT ON COLUMN TBEN753.DAY_NIGHT IS '주간/야간/계절제/원경(D/N/S/R)';
COMMENT ON COLUMN TBEN753.YEAR_LONG IS '수영년한(9.9)';


ALTER TABLE TBEN751
ADD REVERSE_YN VARCHAR2(1);
COMMENT ON COLUMN TBEN751.REVERSE_YN IS '역학기신청 여부(Y/N)';


UPDATE TBEN753_UNIV_202501 SET DAY_NIGHT='D' WHERE DAY_NIGHT='주간';
UPDATE TBEN753_UNIV_202501 SET DAY_NIGHT='N' WHERE DAY_NIGHT='야간';
UPDATE TBEN753_UNIV_202501 SET DAY_NIGHT='S' WHERE DAY_NIGHT='계절제';
UPDATE TBEN753_UNIV_202501 SET DAY_NIGHT='R' WHERE DAY_NIGHT='원격';

UPDATE TBEN753_UNIV_202401 SET DAY_NIGHT='D' WHERE DAY_NIGHT='주간';
UPDATE TBEN753_UNIV_202401 SET DAY_NIGHT='N' WHERE DAY_NIGHT='야간';
UPDATE TBEN753_UNIV_202401 SET DAY_NIGHT='S' WHERE DAY_NIGHT='계절제';
UPDATE TBEN753_UNIV_202401 SET DAY_NIGHT='R' WHERE DAY_NIGHT='원격';

UPDATE TBEN753_UNIV_202302 SET DAY_NIGHT='D' WHERE DAY_NIGHT='주간';
UPDATE TBEN753_UNIV_202302 SET DAY_NIGHT='N' WHERE DAY_NIGHT='야간';
UPDATE TBEN753_UNIV_202302 SET DAY_NIGHT='S' WHERE DAY_NIGHT='계절제';
UPDATE TBEN753_UNIV_202302 SET DAY_NIGHT='R' WHERE DAY_NIGHT='원격';

UPDATE TBEN753_UNIV_202301 SET DAY_NIGHT='D' WHERE DAY_NIGHT='주간';
UPDATE TBEN753_UNIV_202301 SET DAY_NIGHT='N' WHERE DAY_NIGHT='야간';
UPDATE TBEN753_UNIV_202301 SET DAY_NIGHT='S' WHERE DAY_NIGHT='계절제';
UPDATE TBEN753_UNIV_202301 SET DAY_NIGHT='R' WHERE DAY_NIGHT='원격';


UPDATE TBEN753_UNIV_202501 SET YEAR_LONG = REPLACE(YEAR_LONG,'년','');
UPDATE TBEN753_UNIV_202401 SET YEAR_LONG = REPLACE(YEAR_LONG,'년','');
UPDATE TBEN753_UNIV_202302 SET YEAR_LONG = REPLACE(YEAR_LONG,'년','');
UPDATE TBEN753_UNIV_202301 SET YEAR_LONG = REPLACE(YEAR_LONG,'년','');




CREATE INDEX IDX_UNIV_SCH_CD_DEPT_CD ON TBEN753_UNIV_202501 (SCH_CD, SCH_DEPT_CD);
CREATE INDEX IDX_TBEN753_UPDATE ON TBEN753 (ENTER_CD, SCH_LOC_CD, SCH_CD, SCH_DEPT_CD);


UPDATE TBEN753_UNIV_202501 SET SCH_DEPT='자율전공학과' WHERE SCH_DEPT=' 자율전공학과';
UPDATE TBEN753_UNIV_202401 SET SCH_DEPT='자율전공학과' WHERE SCH_DEPT=' 자율전공학과';
UPDATE TBEN753_UNIV_202302 SET SCH_DEPT='자율전공학과' WHERE SCH_DEPT=' 자율전공학과';
UPDATE TBEN753_UNIV_202301 SET SCH_DEPT='자율전공학과' WHERE SCH_DEPT=' 자율전공학과';



UPDATE TBEN753 A
SET
    A.YEAR_LONG = (SELECT B.YEAR_LONG FROM TBEN753_UNIV_202501 B WHERE A.SCH_CD = B.SCH_CD AND A.SCH_DEPT_CD = B.SCH_DEPT_CD),
    A.DAY_NIGHT = (SELECT B.DAY_NIGHT FROM TBEN753_UNIV_202501 B WHERE A.SCH_CD = B.SCH_CD AND A.SCH_DEPT_CD = B.SCH_DEPT_CD)
WHERE
    A.ENTER_CD != 'KS' AND A.SCH_LOC_CD = '0'
    AND EXISTS (
        SELECT 1
        FROM TBEN753_UNIV_202501 B
        WHERE A.SCH_CD = B.SCH_CD
          AND A.SCH_DEPT_CD = B.SCH_DEPT_CD
    );
    
    
UPDATE TBEN753 A
SET
    A.YEAR_LONG = (SELECT B.YEAR_LONG FROM TBEN753_UNIV_202301 B WHERE A.SCH_CD = B.SCH_CD AND A.SCH_DEPT_CD = B.SCH_DEPT_CD AND A.DAY_NIGHT = B.DAY_NIGHT)
WHERE
    A.ENTER_CD != 'KS' AND A.SCH_LOC_CD = '0' 
    AND (A.YEAR_LONG IS NULL OR A.YEAR_LONG=0)
    AND EXISTS (
        SELECT 1
        FROM TBEN753_UNIV_202301 B
        WHERE A.SCH_CD = B.SCH_CD
          AND A.SCH_DEPT_CD = B.SCH_DEPT_CD
          AND A.DAY_NIGHT = B.DAY_NIGHT
    );

UPDATE TBEN753 A
SET
    A.DAY_NIGHT = (SELECT B.DAY_NIGHT FROM TBEN753_UNIV_202301 B WHERE A.SCH_CD = B.SCH_CD AND A.SCH_DEPT_CD = B.SCH_DEPT_CD)
WHERE
    A.ENTER_CD != 'KS' AND A.SCH_LOC_CD = '0' AND A.DAY_NIGHT IS NULL
    AND EXISTS (
        SELECT 1
        FROM TBEN753_UNIV_202301 B
        WHERE A.SCH_CD = B.SCH_CD
          AND A.SCH_DEPT_CD = B.SCH_DEPT_CD
    );
    


UPDATE TBEN753 A
SET
    A.SCH_CAMPUS = (SELECT B.SCH_CAMPUS FROM TBEN753_UNIV_202301 B WHERE A.SCH_CD = B.SCH_CD AND A.SCH_DEPT_CD = B.SCH_DEPT_CD)
WHERE
    A.ENTER_CD != 'KS' AND A.SCH_LOC_CD = '0' AND A.SCH_CAMPUS IS NULL
    AND EXISTS (
        SELECT 1
        FROM TBEN753_UNIV_202301 B
        WHERE A.SCH_CD = B.SCH_CD
          AND A.SCH_DEPT_CD = B.SCH_DEPT_CD
    );
    
    