  CREATE TABLE "PAWS_HG_PRD"."TBEN770" 
   (	"ENTER_CD" VARCHAR2(10 BYTE), 
	"SDATE" VARCHAR2(8 BYTE), 
	"EDATE" VARCHAR2(8 BYTE) DEFAULT '99991231', 
	"MAX_M_AMT" NUMBER, 
	"MAX_Q_AMT" NUMBER, 
	"AGE_LMT" NUMBER, 
	"WRK_D_LMT" NUMBER, 
	"REMARKS" VARCHAR2(2000 BYTE), 
	"CHKID" VARCHAR2(13 BYTE), 
	"CHKDATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_TBEN770" PRIMARY KEY ("ENTER_CD", "SDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSHRD1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSHRD1" ;

   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."ENTER_CD" IS '회사구분코드(TORG900)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."SDATE" IS '기준 시작일자';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."EDATE" IS '기준 종료일자';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."MAX_M_AMT" IS '월간 신청금액 한도 (20만원)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."MAX_Q_AMT" IS '분기 신청금액 한도 (60만원)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."AGE_LMT" IS '나이 제한(만 18세까지)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."WRK_D_LMT" IS '지급대상 필요 근무일수(15일)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."REMARKS" IS '기준 비고';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."CHKID" IS '최종 수정자';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN770"."CHKDATE" IS '최종 수정일시';
   COMMENT ON TABLE "PAWS_HG_PRD"."TBEN770"  IS '특수교육비 기준';

  CREATE INDEX "PAWS_HG_PRD"."IDX_TBEN770_ECD_SD_ED" ON "PAWS_HG_PRD"."TBEN770" ("ENTER_CD", "SDATE", "EDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSHRD1" ;

  CREATE TABLE "PAWS_HG_PRD"."TBEN771" 
   (	"ENTER_CD" VARCHAR2(10 BYTE), 
	"APPL_SEQ" NUMBER, 
	"SABUN" VARCHAR2(13 BYTE), 
	"APP_YEAR" VARCHAR2(4 BYTE), 
	"DIV_CD" NUMBER(1,0), 
	"FAM_NM" VARCHAR2(100 BYTE), 
	"FAM_YMD" VARCHAR2(8 BYTE), 
	"EDU_ORG_NAME" VARCHAR2(100 BYTE), 
	"EDU_CONTENTS" VARCHAR2(2000 BYTE), 
	"APPL_MON1" NUMBER, 
	"APPL_MON2" NUMBER, 
	"APPL_MON3" NUMBER, 
	"APPL_MON" NUMBER, 
	"APPL_NOTE" VARCHAR2(2000 BYTE), 
	"DEPT_CHK_YN" VARCHAR2(1 BYTE), 
	"PAY_AMT" NUMBER, 
	"PAY_YMD" VARCHAR2(8 BYTE), 
	"PAY_YM" VARCHAR2(6 BYTE), 
	"PAY_CNT" NUMBER, 
	"PAY_RETURN" NUMBER, 
	"TAX_YN" VARCHAR2(1 BYTE), 
	"MEMO" VARCHAR2(2000 BYTE), 
	"CHKDATE" DATE DEFAULT SYSDATE, 
	"CHKID" VARCHAR2(13 BYTE), 
	 CONSTRAINT "PK_TBEN771" PRIMARY KEY ("ENTER_CD", "SABUN", "FAM_NM", "FAM_YMD", "APP_YEAR", "DIV_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSHRD1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSHRD1" ;

   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."ENTER_CD" IS '회사구분코드(TORG900)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_SEQ" IS '신청서순번(THRI103)';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."SABUN" IS '사번';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APP_YEAR" IS '신청년도';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."DIV_CD" IS '신청분기';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."FAM_NM" IS '가족성명';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."FAM_YMD" IS '가족생년월일';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."EDU_ORG_NAME" IS '교육기관명';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."EDU_CONTENTS" IS '교육내용';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_MON1" IS '신청금액1';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_MON2" IS '신청금액2';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_MON3" IS '신청금액3';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_MON" IS '신청금액합계';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."APPL_NOTE" IS '신청비고';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."DEPT_CHK_YN" IS '부서확인여부';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."PAY_AMT" IS '지급금액';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."PAY_YMD" IS '지급년월일';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."PAY_YM" IS '급여년월';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."PAY_CNT" IS '지급횟수';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."PAY_RETURN" IS '환수금액';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."TAX_YN" IS '과세여부';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."MEMO" IS '승인비고';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."CHKDATE" IS '최종작성일';
   COMMENT ON COLUMN "PAWS_HG_PRD"."TBEN771"."CHKID" IS '최종작성자';
   COMMENT ON TABLE "PAWS_HG_PRD"."TBEN771"  IS '특수교육비 신청/승인';

