SELECT SUM(NVL(Y.CURR_TOT_MON,0)) AS MON
  FROM THRM100 X
      ,TCPN841 Y
 WHERE X.ENTER_CD = Y.ENTER_CD
   AND X.SABUN    = Y.SABUN
   AND X.ENTER_CD = @@회사코드@@
   AND X.SABUN    = @@사번@@
   AND X.RET_YMD IS NOT NULL
   AND Y.ADJUST_TYPE IN ('1','3')
   AND Y.WORK_YY  = SUBSTR(X.RET_YMD,1,4) - 1